name: Android Firebase CI
'on':
  push:
    branches:
      - firebase_ci
  pull_request:
    branches:
      - firebase_ci
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK v11 and node v14.18.0
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 14.18.0
      - name: build debug
        run: ./gradlew assembleDebug
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
        with:
          appId: '${{secrets.FIREBASE_APP_ID}}'
          token: '${{secrets.FIREBASE_TOKEN}}'
          groups: primaryGroup
          file: app/build/outputs/apk/debug/app-debug.apk
